//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TahilBorsaMS.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbGrainExchangeEntities : DbContext
    {
        public DbGrainExchangeEntities()
            : base("name=DbGrainExchangeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tblAddress> tblAddress { get; set; }
        public virtual DbSet<tblCity> tblCity { get; set; }
        public virtual DbSet<tblContact> tblContact { get; set; }
        public virtual DbSet<tblDistrict> tblDistrict { get; set; }
        public virtual DbSet<tblEntryProduct> tblEntryProduct { get; set; }
        public virtual DbSet<tblFarmer> tblFarmer { get; set; }
        public virtual DbSet<tblLabData> tblLabData { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblRol> tblRol { get; set; }
        public virtual DbSet<tblSale> tblSale { get; set; }
        public virtual DbSet<tblTradesman> tblTradesman { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
    }
}
