//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TahilBorsaMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    
    [Table("tblContact")]
    public partial class tblContact
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Mail { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public bool Process { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Archive { get; set; }
        public Nullable<bool> Important { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> Spam { get; set; }
    }
}
