//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TahilBorsaMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntryProduct
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblEntryProduct()
        {
            this.tblLabData = new HashSet<tblLabData>();
        }
    
        public int Id { get; set; }
        public Nullable<byte> ProductNameId { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<bool> Process { get; set; }
    
        public virtual tblFarmer tblFarmer { get; set; }
        public virtual tblProductName tblProductName { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblLabData> tblLabData { get; set; }
    }
}
