//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TahilBorsaMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblLabData
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<decimal> NutritionalValue { get; set; }
        public Nullable<int> FarmerId { get; set; }
    
        public virtual tblFarmer tblFarmer { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
