//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TahilBorsaMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("tblSale")]
    public partial class tblSale
    {
        public int Id { get; set; }
        public int tblEntryProductId { get; set; }
        public int tblLabDataId { get; set; }
        public decimal BasePrice { get; set; }
        public decimal ActualPrice { get; set; }
        public int Quantity { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> tblTradesmanId { get; set; }
        public DateTime Date { get; set; }
        public Nullable<bool> Process { get; set; }
    
        public virtual tblEntryProduct tblEntryProduct { get; set; }
        public virtual tblLabData tblLabData { get; set; }
        public virtual tblTradesman tblTradesman { get; set; }
    }
}
