//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TahilBorsaMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSaleTrades
    {
        public int Id { get; set; }
        public Nullable<int> SaleId { get; set; }
        public Nullable<int> TradesmanId { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual tblSale tblSale { get; set; }
        public virtual tblTradesman tblTradesman { get; set; }
    }
}
