//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TahilBorsaMS.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblSale()
        {
            this.tblSaleTrades = new HashSet<tblSaleTrades>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LastProductId { get; set; }
        public Nullable<decimal> BasePrice { get; set; }
        public Nullable<decimal> ActualPrice { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual tblLastProduct tblLastProduct { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblSaleTrades> tblSaleTrades { get; set; }
    }
}
